name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  github-pages:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: helaili/jekyll-action@2.2.0
      env:
        JEKYLL_PAT: ${{ secrets.JEKYLL_PAT }}